### ISSUE TITLE
Not working what am i doing wrong?

### ISSUE THREAD

**Issue by DizKiller** [H0nus/SpyNoteShell#1]
I follow your instructions, and it does not work.

here is my input:

┌─[root@parrot]─[/home/MYUSER/Other/SpyNoteShell]
└──╼ #sudo ./spynoteshell.py /home/MYUSER/Desktop/PMPC.apk

here is my output:
Generating payload...
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 8811 bytes
Saved as: temp.apk
[+] Payload created as temp.apk
[*] Decompiling apks...
sh: 1: ./apktool.sh: Permission denied
sh: 1: ./apktool.sh: Permission denied
[*] Injecting payload...
mkdir: cannot create directory ‘PMPC/smali/com/metasploit’: No such file or directory
mkdir: cannot create directory ‘PMPC/smali/com/metasploit/stage’: No such file or directory
cp: cannot stat 'temp/smali/com/metasploit/stage/Payload*': No such file or directory
[-] [Errno 2] No such file or directory: 'PMPC/AndroidManifest.xml'
┌─[root@parrot]─[/home/monolong/Other/SpyNoteShell]
└──╼ #

what am i doing wrong?

**Comment by H0nus** [comment]
Did you set permission to +x?
Into tool dir type:
chmod +x * -R and try again

**Comment by DizKiller** [comment]
Generating payload...
No platform was selected, choosing Msf::Module::Platform::Android from the payload
No Arch selected, selecting Arch: dalvik from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 9439 bytes
Saved as: temp.apk
[+] Payload created as temp.apk
[*] Decompiling apks...
sh: 1: ./apktool.sh: Permission denied
sh: 1: ./apktool.sh: Permission denied
[*] Injecting payload...
mkdir: cannot create directory ‘phonemypclatest/smali/com/metasploit’: No such file or directory
mkdir: cannot create directory ‘phonemypclatest/smali/com/metasploit/stage’: No such file or directory
cp: cannot stat 'temp/smali/com/metasploit/stage/Payload*': No such file or directory
[-] [Errno 2] No such file or directory: 'phonemypclatest/AndroidManifest.xml'

**Comment by H0nus** [comment]
Mmh,stringe thing;
I'll check myself, but first rename the apk to inject as like this -> (example) com.whatsapp.org.apk to whatsapp.apk and keep it out of spynoteshell because that script copy the current apk into directory, so problems can arise;
Keep me updated

**Comment by H0nus** [comment]
Closed nevause no response
